### ISSUE TITLE
No download file for release 3.7.2 & 3.7.3

### ISSUE THREAD

**Issue by 9-9-9-9** [9-9-9-9/Bit-Heroes-bot#113]
Hi @daredoes,

I don't see the down-load-file-file.zip for both [3.7.2](https://github.com/9-9-9-9/Bit-Heroes-bot/releases/tag/release-3.7.2) and [3.7.3](https://github.com/9-9-9-9/Bit-Heroes-bot/releases/tag/release-3.7.3)

Or how long does it take for GHA to append the download file into the release?
___
Thanks for your great effort spent for community.

**Comment by daredoes** [comment]
Can't test it without publishing it :P 

Solved the bug. Release for any new version now happen automatically, and the VERSION is derived from the value in the `VERSION` file at the top level. Gonna do some more changes later to have it auto-create the notes and title and whatnot too. 

Small catch I still need to test. I'm using a `MacOS` runner for the actions because `release.sh` isn't something I can run on the windows runner, I think. Not sure if that breaks builds. If it does, I'll probably rewrite release.sh to be a batch file and switch back to a windows runner

**Comment by 9-9-9-9** [comment]
Yes I always run `release.sh` on Ubuntu & MacOS, never run on Windows before

**Comment by daredoes** [comment]
Great. It'll stay on the macos runner then. Makes it simple since that's what I develop on primarily
