### ISSUE TITLE
Unable to generate mini-client, Reason: None data was provided

### ISSUE THREAD

**Issue by Move4MeNow** [9-9-9-9/Bit-Heroes-bot#60]
Hi there, sorry to boder you, but i dont know what I am doing wrong, well actually I dont know what I am doing.
I followed the steps of "prepare-mini-chrome-client" and then clicked "client" but that error come up, so i dont know whats wrong, hope u can help me.
![miniclient error](https://user-images.githubusercontent.com/93100106/139002114-7b77fc88-b64d-4962-bf24-70c86c8c4515.png)

C:\Program Files (x86)\Google\Chrome\Application\99bot-v2.4.0>del mini-game-on-chrome7.bat  1>nul 2>&1

C:\Program Files (x86)\Google\Chrome\Application\99bot-v2.4.0>del mini-game-on-chrome8.bat  1>nul 2>&1

C:\Program Files (x86)\Google\Chrome\Application\99bot-v2.4.0>del mini-game-on-chrome9.bat  1>nul 2>&1

C:\Program Files (x86)\Google\Chrome\Application\99bot-v2.4.0>del mini-game-on-chrome10.bat  1>nul 2>&1

C:\Program Files (x86)\Google\Chrome\Application\99bot-v2.4.0>call _.bat client

C:\Program Files (x86)\Google\Chrome\Application\99bot-v2.4.0>java -jar BitHeroes.jar client
** WARNING ** You must move the Bit Heroes game's window to top left corner of your screen or provide exactly screen offset into the 'offset.screen.x & y' keys. See more: https://github.com/9-9-9-9/Bit-Heroes-bot/wiki/Manually-setting-game-screen-coordinate
Going to load configuration from user-config.properties
Please give me a Star at my github repository git.bh99bot.com (short link of https://github.com/9-9-9-9/Bit-Heroes-bot). Thank you
Visit our repository often to update latest bot version with new features added frequently
**** ERR ** Unable to generate mini-client!!!
 Reason: None data was provided

**Comment by 9-9-9-9** [comment]
Hi @Move4MeNow
Please remove the # character in the beginning of each lines:

> `# Game token`
> `1.game..................`
> `1.game..................`
> `1.game..................`

The # means commented, not effective so must remove it

There is a trick to have things works more perfectly, that is give me a Star for this project, thank you

**Comment by Move4MeNow** [comment]
thanks, i was able to creat the mini-client, but i still cant use the bot. I tried rerun, but when the rerun botton appear nothing happen, and with fishing the bot is unable to detect mini client, please help again. Star sent!!!
![bhbot error](https://user-images.githubusercontent.com/93100106/139031013-5bf49bdb-c539-4edc-9070-0cb2adf96dc2.png)

**Comment by 9-9-9-9** [comment]
@Move4MeNow there are 2 things I see right now:

1. Are you drag the mini-client bigger than usual? The correct size of mini-client should be 820x565 which just a little bit larger than the game and make some tiny black lines at the right and bottom of the client. Why I see that? Because I see the Minimize, Maximize and the X to close window buttons of the mini-client window are very far away from it. You can try to 

2. Really weird about the error "Can not detect mini-client window". Which Windows version are you using? I have tested on Windows 7 and Windows 10 and bot can detect the mini-client easily. Have you tried this 2.4.0 with Bit Heroes on Steam?

What you can try now:

1. Drag the mini-client to the top left corner of your screen

2. Open the user-config.properties and set the `offset.screen.x` to 8 (or 0, try both) and `offset.screen.y` to 31 and dont forget to remove the `#`
[Read more here](https://github.com/9-9-9-9/Bit-Heroes-bot/wiki/Manually-setting-game-screen-coordinate) 

3. Or even try to launch the bot with Administrator privileges
- Launch a Windows Command Prompt (aka `cmd`) window with Administrator privileges (by right clicking the web.bot.bat file and select `Run as Administrator`)
- `cd` to your bot folder: `cd "C:\Program Files (x86)\Google\Chrome\Application\99bot-v2.4.0"`
- Launch `web.bot.bat` file by just type its name there and Enter _(your Windows hidden the .bat part which is file extension)_

What is it and Why? 
> The bot uses method to scan screen to detect pictures and click them so when auto-detect not work, it doesn't know where to scan so it follows a hard-coded value from user-config and try do detect from it. If can't find picture so it won't work. That's why now you have to try to put those values to `offset.screen.*` keys, it's represent for how much pixel from the left of your screen to the left most of the game (`x`) and same for top (`y`). Make sure you don't have Windows Taskbar at the top of your screen (it usually located at bottom, right?)

**Comment by Move4MeNow** [comment]
1. I did that, and now tried just leave it where its open (image1) but with the same results
![bhbot error2](https://user-images.githubusercontent.com/93100106/139121706-41983ff2-bea0-4976-abf6-2cdd55c32bf1.png)

2. its windows 10, and yes i tried steam bot, fishing works perfectly but ReRun only works 1 Rerun, as soon as it Rerun the pointer goes the top of the screen, and the bot is unable to detect the next rerun, when moving the pointer manualy to the correct place, it works again, but same thing happen (pointer moves at the top of the screen) image2.

![InkedWhatsApp Image 2021-10-27 at 12 47 35_LI](https://user-images.githubusercontent.com/93100106/139121738-1af7b688-dcbf-46b0-9a64-93f0f0db6dbd.jpg)

what can i try:

1. did it same results
2. did it same results (but not sure wich or how many "#" should I delete. ( user-conig image added)
3. when i open the webbot as adm its close immediately, tried several times with the same results, tried just typing enter, it opens, but same results (cant detect mini client window).

Not trying to waste your time here, maybe its me haha, maybe i am not following thecorrect steps or something i dont know, but its ok if is not possible i ll stick with manual playing.

**Comment by 9-9-9-9** [comment]
@Move4MeNow that's really weird!!! And don't worry about wasting my time, haha, welcome welcome.

> when i open the webbot as adm its close immediately, tried several times with the same results, tried just typing enter, it opens, but same results (cant detect mini client window).

So open command prompt separately by press the Windows key on your keyboard, type cmd, right click the CMD.exe and select Run As... and cd to your folder and type web.bot.bat

**Comment by 9-9-9-9** [comment]
About the ReRun on Steam, look like it can detect the ReRun button but it was unable to click the ReRun button, but it thought it was, that's why the counter still decreased (counter decreases after bot sent a click command so bot can see the button)

You can try TEMPORARY disable UAC [read here](https://www.lifewire.com/disable-uac-in-windows-10-5113191) and try again (I just want to make sure it is the Administrator problem)

> Not trying to waste your time here, maybe its me haha, maybe i am not following thecorrect steps or something i dont know, but its ok if is not possible i ll stick with manual playing.

No, Steam doesn't require extra step like mini-client does, your bug is weird and I think it might be caused by UAC, the java (bot) process doesn't have enough privilege to does it's job

**Comment by 9-9-9-9** [comment]
Anyway, I can support via Ultra Viewer (if you wish, we can set a time in UTC+00 and I will remote & check/support you to resolve if I can)

**Comment by Move4MeNow** [comment]
Steambot: I tried disable UAC but was the same results 

Web.bot: manage to cd to the web.bot, but with the same results

![bhbot error](https://user-images.githubusercontent.com/93100106/139506825-468f0618-5863-4264-a8fc-7bfef0cb2956.JPG)

I also tried Rerun, and saids "Starting ReRun" (in blue) but nothing happens.


dont really like the idea of Ultra Viewer, but I ll happy to try an other solution (I hope there is more solutions).

**Comment by 9-9-9-9** [comment]
Hi @Move4MeNow please try this, might helps

https://github.com/9-9-9-9/Bit-Heroes-bot/issues/65#issuecomment-1013632020
